name: CommandSign
version: 1.0.0
author: solo
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\commandsign\CommandSign
permissions:
  commandsign:
    default: op
    children:
      commandsign.install:
        default: true
      commandsign.use:
        default: true
